language: scala
scala:
  - 2.12.7
jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt coverageReport
  - sbt codacyCoverage

after_success:
  - bash < (curl -s https://codecov.io/bash)